### ISSUE TITLE
Piano Addition

### ISSUE THREAD

**Issue by SarahL-C** [gathertown/mapmaking#2]
Hi,

I'm unsure if this is the right way to do it, but I made a piano in 3 different views for my space. Feel free to keep it/modify it/upload it!

-Sarah
![piano_all_views](https://user-images.githubusercontent.com/73563565/107165512-307b0b80-6981-11eb-8eda-17c26f2f22de.png)

**Comment by twostripe** [comment]
This is fantastic, Sarah, thank you so much. I immediately want to use it for our "shared piano" game object.

I made a few minor edits:
- recolored to be in the Gather color palette and to fit more exactly in gather spaces.
- re positioned it slightly to fit better with other furniture
- resized somewhat, to maintain perspective and ratio (using a 3/4 perspective)
- made a up-facing version
- added a "highlited" version, because I want to use this for an interactive object.

Thanks again, expect to see this in the Object Picker by Monday.

![image](https://user-images.githubusercontent.com/14950045/107601675-43d5e300-6bdc-11eb-8f82-1b41259201df.png)
